tap 'heroku/brew'
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/services'
brew 'automake'
brew 'coreutils'
brew 'libksba'
brew 'libtool'
brew 'libyaml'
brew 'postgresql', restart_service: true
brew 'ruby-build'
brew 'rbenv'
brew 'sqlite'
brew 'zlib'
brew 'heroku/brew/heroku'
